import { useEffect, useState } from 'react';
import { listOsasPermissionRows, setOsasPermissions, type OsasPermissionRow } from './osas-data';
export type PermissionAdmin = { id: string; email: string; displayName: string; role: 'admin' | 'super_admin'; isActive: boolean; createdAt: string };
export function OsasPermissions({ admins }: { admins: PermissionAdmin[] }) {
  const [rows, setRows] = useState<OsasPermissionRow[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setRows(await listOsasPermissionRows()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load OSAS permissions.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const change = async (admin: PermissionAdmin, field: 'aggregate' | 'support', checked: boolean) => { const current = rows.find(row => row.user_id === admin.id); const view = field === 'aggregate' ? checked : current?.can_view_aggregates ?? false; const support = field === 'support' ? checked : current?.can_manage_support_requests ?? false; setSaving(admin.id); setError(''); setNotice(''); try { await setOsasPermissions(admin.id, view, support, true); await load(); setNotice(view || support ? `OSAS permissions updated for ${admin.email}.` : `OSAS permissions revoked for ${admin.email}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update OSAS permissions.'); } finally { setSaving(null); } };
  return <section className="panel table-panel"><div className="table-toolbar"><div><h2>OSAS permissions</h2><p>These permissions are separate from general administrator access.</p></div><button className="secondary-button" onClick={() => void load()}>Refresh</button></div>{notice && <div className="case-notice" role="status">{notice}</div>}{error && <div className="empty-state">Could not load OSAS permissions: {error}</div>}{loading ? <div className="empty-state">Loading OSAS permissions...</div> : <div className="permission-list"><div className="permission-row permission-header"><span>PERSONNEL</span><span>ADMIN STATUS</span><span>AGGREGATE REPORTS</span><span>IDENTIFIABLE SUPPORT CASES</span></div>{admins.map(admin => { const permission = rows.find(row => row.user_id === admin.id); const disabled = !admin.isActive || saving === admin.id; return <div className="permission-row" key={admin.id}><div className="row-copy"><b>{admin.displayName}</b><small>{admin.email}</small></div><span className={`status ${admin.isActive ? 'active' : 'inactive'}`}><i />{admin.isActive ? 'Active' : 'Inactive'}</span><label className="permission-toggle"><input type="checkbox" checked={permission?.can_view_aggregates ?? false} disabled={disabled} onChange={event => void change(admin, 'aggregate', event.target.checked)} /><span>{permission?.can_view_aggregates ? 'Granted' : 'Not granted'}</span></label><label className="permission-toggle"><input type="checkbox" checked={permission?.can_manage_support_requests ?? false} disabled={disabled} onChange={event => void change(admin, 'support', event.target.checked)} /><span>{permission?.can_manage_support_requests ? 'Granted' : 'Not granted'}</span></label></div>; })}</div>}<p className="permission-note">Inactive administrators have no effective OSAS access even if a stored permission row exists. Clearing both permissions revokes and removes that row.</p></section>;
}
