import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { listSupportRequests, listSupportStaff, updateSupportRequest, type OsasSupportRequest, type OsasSupportStaff } from './osas-data';
const STATUS_OPTIONS = ['', 'submitted', 'acknowledged', 'in_progress', 'resolved', 'withdrawn'];
const CATEGORY_OPTIONS = ['', 'academic', 'personal', 'wellbeing', 'financial', 'safety', 'other'];
const LABELS: Record<string, string> = { submitted: 'Submitted', acknowledged: 'Acknowledged', in_progress: 'In progress', resolved: 'Resolved', withdrawn: 'Withdrawn', wellbeing: 'Well-being', in_person: 'In person', in_app: 'In app' };
const label = (value: string) => LABELS[value] ?? value.charAt(0).toUpperCase() + value.slice(1);
export function SupportRequests() {
  const [requests, setRequests] = useState<OsasSupportRequest[]>([]); const [staff, setStaff] = useState<OsasSupportStaff[]>([]); const [selected, setSelected] = useState<OsasSupportRequest | null>(null);
  const [status, setStatus] = useState(''); const [category, setCategory] = useState(''); const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [cases, people] = await Promise.all([listSupportRequests(status || null), listSupportStaff()]); setRequests(cases); setStaff(people); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load support requests.'); setRequests([]); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [status]);
  const visible = useMemo(() => requests.filter(request => { const term = search.trim().toLowerCase(); const matchesSearch = !term || [request.student_name, request.student_number, request.student_email, request.message].some(value => value?.toLowerCase().includes(term)); const created = request.created_at.slice(0, 10); return matchesSearch && (!category || request.category === category) && (!from || created >= from) && (!to || created <= to); }), [requests, search, category, from, to]);
  return <><section className="panel table-panel support-panel"><div className="table-toolbar"><div><h2>Identifiable support cases</h2><p>Visible only to personnel with OSAS support-management permission.</p></div><button className="secondary-button" onClick={() => void load()}>Refresh</button></div><div className="case-filters"><label>Search<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Student, number, email, or concern" /></label><label>Status<select value={status} onChange={event => setStatus(event.target.value)}>{STATUS_OPTIONS.map(value => <option value={value} key={value}>{value ? label(value) : 'All statuses'}</option>)}</select></label><label>Category<select value={category} onChange={event => setCategory(event.target.value)}>{CATEGORY_OPTIONS.map(value => <option value={value} key={value}>{value ? label(value) : 'All categories'}</option>)}</select></label><label>From<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div>{notice && <div className="case-notice" role="status">{notice}</div>}{error && <div className="empty-state">Could not load support cases: {error}</div>}{loading ? <div className="empty-state">Loading support cases...</div> : visible.length === 0 ? <div className="empty-state">No support requests match these filters.</div> : <div className="case-list">{visible.map(request => <button className="case-row" onClick={() => setSelected(request)} key={request.id}><div><b>{request.student_name}</b><small>{request.student_number} · {request.course} · {request.campus}</small></div><span>{label(request.category)}</span><span className={`status case-${request.status}`}><i />{label(request.status)}</span><span>{new Date(request.created_at).toLocaleString()}</span><strong>{label(request.priority)}</strong></button>)}</div>}</section>{selected && <CaseDrawer request={selected} staff={staff} saving={saving} onClose={() => setSelected(null)} onSave={async (nextStatus, assignedTo, note) => { setSaving(true); setError(''); try { await updateSupportRequest(selected.id, nextStatus, assignedTo, note); await load(); setSelected(null); setNotice('Support case updated.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update the case.'); } finally { setSaving(false); } }} />}</>;
}
function CaseDrawer({ request, staff, saving, onClose, onSave }: { request: OsasSupportRequest; staff: OsasSupportStaff[]; saving: boolean; onClose: () => void; onSave: (status: 'acknowledged' | 'in_progress' | 'resolved', assignedTo: string | null, note: string | null) => Promise<void> }) {
  const editable = request.status !== 'withdrawn'; const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void onSave(data.get('status') as 'acknowledged' | 'in_progress' | 'resolved', String(data.get('assignedTo') || '') || null, String(data.get('note') || '').trim() || null); };
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer case-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" onClick={onClose}>×</button><span className="eyebrow">OSAS SUPPORT CASE</span><h2>{request.student_name}</h2><p className="drawer-muted">{request.student_number} · {request.student_email}</p><span className={`status case-${request.status}`}><i />{label(request.status)}</span><div className="detail-grid"><div><small>CATEGORY</small><b>{label(request.category)}</b></div><div><small>PRIORITY</small><b>{label(request.priority)}</b></div><div><small>PREFERRED CONTACT</small><b>{label(request.preferred_contact)}</b></div><div><small>CONTACT DETAIL</small><b>{request.contact_detail || request.student_email}</b></div><div><small>SUBMITTED</small><b>{new Date(request.created_at).toLocaleString()}</b></div><div><small>UPDATED</small><b>{new Date(request.updated_at).toLocaleString()}</b></div></div><h3>Student concern</h3><p className="case-message">{request.message}</p>{request.resolution_note && <div className="case-followup"><b>Recorded follow-up</b><p>{request.resolution_note}</p>{request.resolved_at && <small>Resolved {new Date(request.resolved_at).toLocaleString()}</small>}</div>}{editable ? <form className="case-form" onSubmit={submit}><label>Status<select name="status" defaultValue={request.status === 'submitted' ? 'acknowledged' : request.status}><option value="acknowledged">Acknowledged</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></label><label>Assign to<select name="assignedTo" defaultValue={request.assigned_to ?? ''}><option value="">Unassigned</option>{staff.map(person => <option value={person.id} key={person.id}>{person.display_name} ({person.email})</option>)}</select></label><label>Follow-up or resolution note<textarea name="note" maxLength={2000} defaultValue={request.resolution_note ?? ''} rows={5} placeholder="Record completed follow-up or the resolution. Do not imply actions that have not occurred." /></label><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : 'Save case update'}</button></form> : <div className="case-followup"><b>Withdrawn by student</b><p>This case is read-only and cannot be updated.</p></div>}</aside></div>;
}
