import React, {useSyncExternalStore} from 'react';
const listeners=new Set<()=>void>(); export const actions:any[]=[];
export const qs:any[]=[{id:'q1',title:'Review notes for tomorrow’s class',description:'Give yourself a focused twenty minutes to review your notes and identify what you want to ask in class.',category:'Academics',xp:25,status:'active',requires_proof:false,owner_id:'synthetic',created_at:'2026-10-06T01:00:00Z',deadline_at:'2026-10-07T09:00:00Z'}, {id:'q2',title:'Take a short walk between study sessions',description:'Step outside and stretch.',category:'Health',xp:15,status:'active',requires_proof:true,owner_id:'synthetic',created_at:'2026-10-05T01:00:00Z'}, {id:'q3',title:'Organize this week’s reading list',category:'Habits',xp:20,status:'active',owner_id:'synthetic',created_at:'2026-10-04T01:00:00Z',prerequisite_quest_id:'missing'}, {id:'q4',title:'Meet with my study group',category:'Social',xp:30,status:'pending',owner_id:'synthetic',created_at:'2026-10-03T01:00:00Z'}, {id:'q5',title:'Finish a practice exercise',category:'Academics',xp:20,status:'completed',owner_id:'synthetic',created_at:'2026-10-02T01:00:00Z'}];
const ok=async(...args:any[])=>{actions.push(args); return {success:true,status:'completed'}};
export const data:any={user:{id:'synthetic',email:'student@example.test'},access:'active',profile:{id:'synthetic',display_name:'Alex Reyes',name:'Alex Reyes',email:'student@example.test',student_number:'123456789',course:'BSCS',year_level:'4',section:'2',campus:'Main',goal:'Build a steady study routine',total_xp:240,level:3,current_streak:3},quests:qs,completionHistory:[{id:'history-1',title:'Finish a practice exercise',category:'Academics',completed_at:'2026-10-05T12:00:00Z',xp:20}],progressSummary:{totalCompleted:12,byCategory:{Academics:5,Habits:4,Social:1,Health:2}},levelProgress:{level:3,currentLevelXp:40,xpForNextLevel:100,progressPercent:40},workspaceErrors:{},refresh:ok,retryWorkspace:ok,completeQuest:async(...args:any[])=>{actions.push(['complete',...args]);return {success:true}},deleteQuest:ok,addQuest:ok,updateQuest:ok,updateProfile:ok,signOut:ok,signIn:ok,signUp:ok,resendConfirmation:ok,requestPasswordReset:ok,updateRecoveryPassword:ok,completeRegistration:ok,isLoading:false,isRefreshing:false,isSigningOut:false,isAuthBusy:false,registrationEmail:'student@example.test'};
export function useUserData(){return data}
export function useQuestPriority(){return {ranked:qs.map((quest,i)=>({quest,tier:quest.status==='completed'?'history':'available',reasons:['Fits your study goal','Due tomorrow'],reasonCodes:['goal_alignment'],nearby:false,locked:!!quest.prerequisite_quest_id})),locationAvailable:false,now:Date.now()}}
let params:any={};let revision=0;function update(){revision++;listeners.forEach(fn=>fn())}
export const router={push:(v:any)=>actions.push(['push',v]),back:()=>actions.push(['back']),setParams:(v:any)=>{params={...params,...v};update()}};
export function useLocalSearchParams(){useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>revision);return params}
export function useFocusEffect(fn:any){React.useEffect(fn,[fn])}
export function useEnrollmentOptions(){return {options:[{id:'option1',semester_id:'semester1',academic_year:'2026-2027',term:'First semester',course:'BSCS',year_level:'4',section:'2',campus:'Main'}],loading:false,error:null,retry:ok}}
export function useQuestCategories(){return {categories:['Academics','Habits','Social','Health'].map((name,i)=>({id:String(i),name})),loading:false,error:null,refresh:ok,createCategory:ok}}
export function useLocationContext(){return {locations:[],activeLocations:[],isLoading:false,coords:null,addLocation:ok,updateLocation:ok,deleteLocation:ok,toggleActive:ok,requestPermissions:ok,getCurrentPosition:async()=>null}}
export const listMyCheckIns=async()=>[];export const listMyReflections=async()=>[];export const listMySupportRequests=async()=>[];export const saveMyCheckIn=ok;export const createMyReflection=ok;export const createMySupportRequest=ok;export const withdrawMySupportRequest=ok;
export const recordRecommendationEvent=ok;export const createRecommendationSession=()=> 'synthetic';
export const useQuestNotificationStatus=()=> 'ready';export const retryQuestNotifications=ok;export const questNeedsOpen=(q:any)=>!!q.requires_proof||!!q.prerequisite_quest_id;
(window as any).__ui={data,actions,qs,router,update};
