// Isolated static screenshot harness. No Auth client or Supabase requests.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),http=require('node:http'),cp=require('node:child_process');const mobile=path.resolve(__dirname,'../..');const React=require('react'),RN=require('react-native-web'),ReactDOM=require('react-dom/server'),ts=require('typescript');const glyphs=require('@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Ionicons.json');
function render(screen,width,scheme,scale=1,detail='',scenario='',baseline=false){
 const cache=new Map(),window={};const react={...React,useState:initial=>React.useState(scenario==='settled'&&initial===true?false:scenario==='all'&&initial==='context'?'all':initial)};const rn={...RN,Modal:({visible,children,...props})=>visible?React.createElement(RN.View,props,children):null,Text:props=>{const s=RN.StyleSheet.flatten(props.style)||{};return React.createElement(RN.Text,{...props,style:[props.style,scale!==1&&s.fontFamily!=='Ionicons'&&props.allowFontScaling!==false?{fontSize:(s.fontSize||16)*scale,lineHeight:(s.lineHeight||24)*scale}:{}]})},useColorScheme:()=>scheme,useWindowDimensions:()=>({width,height:812,scale:1,fontScale:scale})};
 const load=file=>{if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const code=ts.transpileModule(baseline&&file.includes(path.join(mobile,'src'))?cp.execFileSync('git',['show','HEAD:mobile/'+path.relative(mobile,file).replaceAll('\\','/')],{cwd:path.dirname(mobile),encoding:'utf8'}):fs.readFileSync(file,'utf8'),{fileName:file,compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
 vm.runInNewContext(code,{module,exports:module.exports,require:name=>{if(name.endsWith('.css'))return {};if(name==='react')return react;if(name==='react-native')return rn;if(name==='react/jsx-runtime')return require(name);if(name==='react-native-safe-area-context')return {SafeAreaView:RN.View,SafeAreaProvider:RN.View,useSafeAreaInsets:()=>({top:0,left:0,right:0,bottom:0})};if(name==='@expo/vector-icons')return {Ionicons:({name,size,color,...props})=>React.createElement(RN.Text,{...props,style:{fontFamily:'Ionicons',fontSize:size,color}},String.fromCodePoint(glyphs[name]||glyphs['ellipse-outline']))};if(name==='react-native-svg')return {__esModule:true,default:p=>React.createElement('svg',p),Line:p=>React.createElement('line',p)};if(name==='expo-image-picker'||name==='expo-document-picker')return {};if(name==='expo-linking')return {createURL:()=> 'beebetter://auth'};if(name==='@/hooks/use-color-scheme')return {useColorScheme:()=>scheme};if(name==='react-native-maps')return {__esModule:true,default:RN.View,Circle:RN.View,Marker:RN.View};if(name==='expo-router/ui')return {Tabs:RN.View,TabSlot:()=>null,TabList:RN.View,TabTrigger:({children,name})=>React.cloneElement(children,{isFocused:name===({home:'index',quests:'quests',profile:'profile',skills:'skill-tree'})[screen]})};if(name==='@/hooks/use-theme')return {useTheme:()=>load(path.join(mobile,'src/constants/theme.ts')).Colors[scheme]};
 const mocks=['@/hooks/use-user-data','@/context/user-data-context','@/context/quest-priority-context','@/context/location-context','@/hooks/use-enrollment-options','@/hooks/use-quest-categories','@/lib/wellbeing-data','@/lib/recommendation-events','@/lib/quest-notifications','expo-router'];if(mocks.includes(name)){const m=load(path.join(__dirname,'fixtures.tsx'));m.useLocalSearchParams=()=>({questId:detail});if(screen==='auth')m.data.access=scenario==='recovery'?'recovery_required':'signed_out';if(scenario==='partial')m.data.workspaceErrors={quests:'Could not refresh quests. Check your connection.',progress:'Could not refresh progress.'};if(scenario==='empty')m.qs.length=0;if(scenario==='long'){m.data.profile.display_name='Alexandra Reyes with a longer display name';m.qs[0].title='Prepare my reading notes and review the most important questions for the upcoming student discussion';}return m;}
 if(name.startsWith('@/')||name.startsWith('.')){const base=name.startsWith('@/')?path.join(mobile,'src',name.slice(2)):path.resolve(path.dirname(file),name);for(const ext of ['.web.tsx','.web.ts','.tsx','.ts','.js',''])if(fs.existsSync(base+ext)&&fs.statSync(base+ext).isFile())return load(base+ext);throw Error('Missing '+name)}return require(name);},window,console,setTimeout,clearTimeout,URL,URLSearchParams,Date},{filename:file});return module.exports;};
 const files={home:'app/(tabs)/index.tsx',quests:'app/(tabs)/quests.tsx',profile:'app/(tabs)/profile.tsx',skills:'app/(tabs)/skill-tree.tsx',create:'app/add-quest.tsx',checkin:'app/wellness-check-in.tsx',reflection:'app/self-management-reflection.tsx',history:'app/wellness-history.tsx',support:'app/support-requests.tsx',notifications:'app/notifications.tsx',auth:'app/auth.tsx',onboarding:'components/student-onboarding.tsx',places:'app/manage-locations.tsx'};
 const mod=load(path.join(mobile,'src',files[screen]||files.home)),Screen=mod.default||mod.StudentOnboarding;
 const tabs=['home','quests','profile','skills'].includes(screen)&&!detail?load(path.join(mobile,'src/components/app-tabs.web.tsx')).default:null;const html=ReactDOM.renderToStaticMarkup(React.createElement(React.Fragment,null,React.createElement(Screen),tabs&&React.createElement(tabs)));const css=RN.StyleSheet.getSheet().textContent;
 return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeeBetter synthetic screen</title><style>'+css+'@font-face{font-family:Ionicons;src:url(/ionicons.ttf)}:root{--font-display:system-ui,sans-serif;--font-mono:monospace}html,body,#root{margin:0;min-height:100vh}#root{display:flex;flex-direction:column}body{background:'+(scheme==='dark'?'#181A1E':'#F7F8FA')+'}</style></head><body><div id="root">'+html+'</div></body></html>';
}
http.createServer((req,res)=>{if(req.url==='/ionicons.ttf'){res.setHeader('Content-Type','font/ttf');res.end(fs.readFileSync(require.resolve('@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf')));return}try{const q=new URL(req.url,'http://localhost').searchParams;res.setHeader('Content-Type','text/html; charset=utf-8');res.end(render(q.get('screen')||'home',Number(q.get('width')||375),q.get('theme')||'light',Number(q.get('scale')||1),q.get('detail')||'',q.get('scenario')||'',q.get('baseline')==='1')); }catch(error){console.error(error.message);res.statusCode=500;res.end(error.stack)}}).listen(8081,'127.0.0.1',()=>console.log('Static synthetic UI: http://127.0.0.1:8081/preview'));
